config/routes.rb
Rails.application.routes.draw do
  get 'students/index'

  get 'sessions/login'
  post 'sessions/login'
  get 'sessions/logout'
  post 'sessions/logout'

  resources :assignments, except: [:destroy]
  resources :submissions, except: [:show, :update, :destroy]

  root 'assignments#index'
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :teacher
  has_many :submissions
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  belongs_to :teacher
  has_many :submissions

  def name
    user.name
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :assignment
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :user
  has_many :students
  has_many :assignments

  def name
    user.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :teacher
  has_one :student

  def is_teacher?
    teacher ? true : false
  end

  def is_student?
    student ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :teacher?, :student?


  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def check_user
    if current_user.nil?
      redirect_to sessions_login_path
    end
  end

  def teacher?
    current_user.is_teacher?
  end

  def student?
    current_user.is_student?
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  respond_to :html, :json

  before_action :check_user
  before_action :set_assignment, only: [:edit, :update, :show]

  def index
    @assignments = Assignment.all
    # TODO write a method in assignment model to get assignments
    # TODO figure out a better way to parse the assignment description,
    # something like /300characters and then a newline/
  end

  def show
    if student?
      session[:assignment_id] = @assignment.id
      redirect_to new_submission_path
    end
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to assignments_path
    else
      render 'new'
    end
  end

  def edit
    redirect_to @assignment if student?
  end

  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignments_path }
        format.json { respond_with @assignment }
      else
        render 'edit'
      end
    end
  end

  private def assignment_params
    params.require(:assignment).permit(:name, :description, :due_at, :visable, :teacher_id)
  end

  private def set_assignment
    @assignment = Assignment.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    if request.post?
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to sessions_login_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :check_user
  def index
    @teachers = Teacher.all
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :update]

  def index

  end

  def new
    @submission = Submission.new
    @assignment = Assignment.find(session[:assignment_id])
  end

  def create
    submission = Submission.new(submission_params)
    if submission.save
      session[:assignment_id] = nil # TODO there has to be a better way
      redirect_to assignments_path
    else
      render 'new'
    end
  end

  private def set_submission
    @submission = Submission.find(params[:id])
  end

  private def submission_params
    params.require(:submission).permit(:repository, :application ,:student_id, :assignment_id, :submitted_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/assignments/_card.html.erb
<div id="assignments">
  <div class="cards">
    <div class="card">
      <div class="card-copy">
        <%= markdown(assignment.description) %>
      </div>
    </div>
  </div>
</div>

app/views/assignments/_form.html.erb
<section class = "assignment_form">
  <%= form_for(@assignment) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field date">
    <%= f.label :due_at %><br>
    <%= f.datetime_select :due_at %>
  </div>

  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visable %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</section>

app/views/assignments/_student_assignment.html.erb
<h1>Student's Assignment show</h1>

app/views/assignments/_submission.html.erb
<%= submission.repository %>

app/views/assignments/_submission_card.html.erb
<div class="card">
  <div class="card-copy">
    <%= link_to s.student.name, '#' %>
  </div>
  <div class="card-copy">
    <%= link_to "Github", s.repository %>
  </div>
  <% if s.application %>
    <div class="card-copy">
      <%= link_to "Application", s.application %>
    </div>
  <% end %>
</div>

app/views/assignments/_teacher_assignment.html.erb
<h1>Teacher's Assignment show</h1>

<%= @assignment.submissions.each do |s| %>
<% end %>

app/views/assignments/edit.html.erb
Visable? <%= best_in_place(@assignment, :visable, :as => :checkbox) %>


<label class="label-switch">
    <div class="checkbox"></div>
</label>
<%= render partial: 'card', :locals => { assignment: @assignment } %>
<p><%= best_in_place @assignment, :description, :as => :textarea %></p>


<%= render 'form' %>

<script>
    $(document).ready(function() {
      jQuery(".best_in_place").best_in_place();
      });
</script>

app/views/assignments/index.html.erb
<div id="assignments">
  <div class="cards">
    <% @assignments.each do |a| %>
      <% if a.visable || teacher? %>
        <div class="card">
          <div class="card-header">
            <%= link_to a.name, a %>
          </div>
          <% if teacher? %>
            <div class="card-header">
              Visable: <%= a.visable %>
            </div>
          <% end %>
          <div class="card-copy">
            <%= markdown(a.description[0..300] + "\n...") %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

app/views/assignments/show.html.erb
<% if teacher? %>
  <div class="cards">
    <% @assignment.submissions.each do |s| %>
      <%= render partial: 'submission_card', :locals => {:s => s} %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<footer class="footer-2" role="contentinfo">
  <ul>
    <li><%= link_to "Assignments", assignments_path %></li>
  </ul>

  <div class="footer-secondary-links">
    <ul>
      <li><%= link_to current_user.name, '#' %></li>
      <li><%= link_to 'Logout', sessions_logout_path %></li>
    </ul>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Report Card</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= render '/layouts/nav' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

<% @teachers.each do |t| %>
  <h2> <%= t.name %>'s students </h2>
  <% t.students.each do |s| %>
    <p> <%= s.name %> </p>
  <% end %>
<% end %>

app/views/submissions/_form.html.erb
<section class = "submission_form">
  <%= form_for(@submission) do |f| %>
    <div class="field">
      <%= f.hidden_field :student_id, value: current_user.student.id %>
    </div>

    <div class="field">
      <%= f.hidden_field :assignment_id, value: session[:assignment_id] %>
    </div>

    <div class="field">
      <%= f.hidden_field :submitted_at, value: DateTime.now %>
    </div>

    <div class="field">
      <%= f.label :repository %><br>
      <%= f.text_area :repository %>
    </div>

    <div class="field">
      <%= f.label :application %><br>
      <%= f.text_area :application %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</section>

app/views/submissions/new.html.erb
<%= render 'form' %>
<div class="cards">
  <div class="card">
    <div class="card-copy">
      <%= markdown(@assignment.description) %>
    </div>
  </div>
</div>